services:
  - type: worker
    name: padel-scraper-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    postBuildCommand: python -m playwright install chromium
    startCommand: python padelv2.py
